#默认使用配置
spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
#公共配置与profiles选择无关
mybatis-plus:
  typeAliasesPackage: com.cn.commodity.entity
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    com.cn.commodity.dao: debug

config:
  path:
    #该路径下GET请求放行，其他拦截
    normal:

    #该路径下任何类型请求均拦截
    special:
      - /showUser
    #该路径下任何请求均放行
    exclude:
      - /mybatisPlus

server:
  port: 8000
apache:
  rocketmq:
    #消费者的配置
    consumer:
      pushConsumer: myConsumer
    #生产者的配置
    producer:
      producerGroup: myGroup
    namesrvAddr: 127.0.0.1:9876

---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/test
    username: root
    password: yang156122
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

#jasypt:
#  encryptor:
#    password: yangwj

---
#开发配置
spring:
  profiles: test

  datasource:
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/test
    username: root
    password: yang156122
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource